@startuml
'https://plantuml.com/sequence-diagram

class Notification {
    -String title,message,icon,sound,priority,actionButtons


}
class NotificationBuilder {
    -String title,message,icon,sound,priority,actionButtons
    +Build ti
}

NotificationBuilder..>Notification
@enduml